service: PRDStarter

useDotenv: true
configValidationMode: error

package:
  artifact: .build/lambda/PRDStarter/lambda.zip

custom:
  apiKey-dev: da39a3ee5e6b4b0d3255bfef95601890afd80709
  apiKey-prod: 3da541559918a808c2402bba5012f6c60b27661c
  
provider:
  name: aws
  runtime: provided
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  profile: fuzztival
  # architecture: arm64
  environment:
    CONFLUENCE_API_KEY: ${env:CONFLUENCE_API_KEY}
    GATEWAY_URL: ${env:GATEWAY_URL}
    ENTRYPOINT_URL: https://mogzv5pkef.execute-api.us-west-2.amazonaws.com/dev
    AWS_ACCESS_KEY_ID1: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY1: ${env:AWS_SECRET_ACCESS_KEY}
    
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - es:ESHttpPost
            - es:ESHttpPut
          Resource: "*"


functions:
  base:
    handler: handle
    memorySize: 1024
    timeout: 300
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
   

